import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-white h-[4rem] w-[100vw] flex justify-start items-center">
          <div className="flex w-[50%] justify-center items-center">
            <a href="/login">
              {" "}
              <img src="img/Logo.png" alt="logo" />
            </a>
          </div>
          <div>&nbsp;</div>
        </header>
        {children}
      </body>
    </html>
  );
}
